/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
   @Test
    public void addTest(){
       HashTable hashTest = new HashTable(5);
       hashTest.add(2,"tamara");
       hashTest.add(1,"jood");
       hashTest.add(1,"lama");
       assertEquals("tamara",hashTest.get(2));
       assertNull(hashTest.get(3));
       assertEquals(hashTest.contain(4),false);
       assertEquals(hashTest.get(1),"lama");





   }
}
