/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package isertionSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

        @Test
        public void insertionSortTest() {
            Library classUnderTest = new Library();
            int[]arr={8,4,23,42,16,15};
            int[]arr2={};
            assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString( classUnderTest.insertionSort(arr)));
            assertEquals("[]", Arrays.toString( classUnderTest.insertionSort(arr2)));


        }
}
